# rtclive api server
server:
  host: 127.0.0.1
  port: 5000

  
# webrtc media server address, the endpoint should be a public server ip, if you use rtclive in production
media:
  endpoint: 127.0.0.1
  minport: 20000
  maxport: 60000



relay: 
  host: 127.0.0.1
  port: 1936




# rtmp server listen addr
rtmp:
  host: 127.0.0.1
  port: 1935


# rtclive support server relay, when rtclive server can not find one stream, it will find stream from origin servers.
# you can config multi origin servers.
# it is the origin's http server address
# cluster:
#   origins:
#     - 127.0.0.1:5001


# webrtc media capability
capability:
  audio:
    codecs:
      - opus
    extensions:
      - urn:ietf:params:rtp-hdrext:ssrc-audio-level
      - http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
  video:
    codecs:
      - h264
    rtx: true
    rtcpfbc:
      - id: goog-remb
      - id: transport-cc
      - id: ccm
        params: [fir]
      - id: nack
      - id: nack
        params: [pli]
    extensions:
      - urn:3gpp:video-orientation
      - http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
      - http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
      - urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
      - urn:ietf:params:rtp-hdrext:sdes:mid
